### ISSUE TITLE
source data not included

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/bc_population_indicator#1]
Can I ask that you please include the two csv files with the source data in the repo? Thanks

**Comment by stephhazlitt** [comment]
Hi @MonkmanMH. We don't usually include source data in the repositories for a few reasons (e.g. large file sizes, source data is not available under an open license). The ['inspiration'](https://github.com/BCDevExchange/Our-Project-Docs/blob/master/discussion/projectstates.md) tag means we are just exploring this concept-idea, however we will ensure the data is available programmatically once we have moved to the ['exploration'](https://github.com/BCDevExchange/Our-Project-Docs/blob/master/discussion/projectstates.md) phase of this work. In the meantime, I will comment the code to ensure users can locate the source data from the various public/on-line sources.
